import React, { useState } from "react";
import "../assets/styles/TopColleges.css";

const TopColleges = () => {
  const [selectedCourse, setSelectedCourse] = useState("All");

  const handleCourseClick = (course) => {
    setSelectedCourse(course);
  };

  const collegesData = {
    All: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp", 
        name: "IIT Bombay - Indian Institute of Technology",
        location: "Mumbai city, Maharashtra | ⭐ 5/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 68",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,30,700 (1st Year Fees)",
      }, {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkharagpur.webp",
        name: "IIT Kharagpur - Indian Institute of Technology",
        location: "Kharagpur, West Bengal | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#6 out of 200 in India 2024",
        cutoff: "CAT 2024 Cut off 90",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,62,360 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "IIT Delhi - Indian Institute of Technology [IITD]",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#1 out of 27 in India 2024",
        cutoff: "CAT 2024 Cut off 98",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,28,650 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitmadras.webp",
        name: "IIT Madras - Indian Institute of Technology [IITM]",
        location: "Chennai, Tamil Nadu | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#1 out of 200 in India 2024",
        cutoff: "CAT 2024 Cut off 85",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,42,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iima.webp",
        name: "IIMA - Indian Institute of Management",
        location: "Ahmedabad, Gujarat | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/iima.webp",
        ranking: "#2 out of 50 in India 2019",
        cutoff: "CAT 2024 Cut off 99",
        applicationDeadline: "03 Dec 2024",
        fees: "₹33,00,000 (Total Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "IIT Kanpur - Indian Institute of Technology [IITK]",
        location: "Kanpur, Uttar Pradesh | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#4 out of 27 in India 2024",
        cutoff: "CAT 2024 Cut off 85",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,29,970 (1st Year Fees)",
      },
      {
        rank: "#7",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "IIT Roorkee - Indian Institute of Technology [IITR]",
        location: "Roorkee, Uttarakhand | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#5 out of 27 in India 2024",
        cutoff: "CAT 2024 Cut off 95",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,30,100 (1st Year Fees)",
      },
      {
        rank: "#8",
        logo: "/assets/collegenamelogos/iimbbanglore.webp",
        name: "IIM Bangalore - Indian Institute of Management",
        location: "Bangalore, Karnataka | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/banglore.webp",
        ranking: "#1 out of 50 in India 2019",
        cutoff: "CAT 2024 Cut off 99",
        applicationDeadline: "21 June - 07 Aug 2024",
        fees: "₹1,25,000 (1st Year Fees)",
      },
      {
        rank: "#9",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "IIT Guwahati - Indian Institute of Technology [IITG]",
        location: "Guwahati, Assam | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#6 out of 27 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 1021",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,88,250 (1st Year Fees)",
      },
      {
        rank: "#10",
        logo: "/assets/collegenamelogos/bitspilani.webp",
        name: "BITS Pilani (Pilani Campus)",
        location: "Pilani, Rajasthan | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/pilani.webp",
        ranking: "#19 out of 200 in India 2024",
        cutoff: "CAT 2024 Cut off 80",
        applicationDeadline: "18 May - 08 Jun 2024",
        fees: "₹5,71,575 (1st Year Fees)",
      },
    ],
    MBA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iimbbanglore.webp",
        name: "IIM Bangalore - Indian Institute of Management",
        location: "Bangalore, Karnataka | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/bangalore.webp",
        ranking: "#1 out of 50 in India 2019",
        cutoff: "CAT 2024 Cut off 99",
        applicationDeadline: "21 June - 07 Aug 2024",
        fees: "₹1,25,000 (1st Year Fees)",
      },

      // Add more MBA colleges
    ],
    BTech: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp", 
        name: "IIT Bombay - Indian Institute of Technology",
        location: "Mumbai city, Maharashtra | ⭐ 5/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 68",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,30,700 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkharagpur.webp",
        name: "IIT Kharagpur - Indian Institute of Technology",
        location: "Kharagpur, West Bengal | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#6 out of 200 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 90",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,62,360 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "IIT Delhi - Indian Institute of Technology [IITD]",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#1 out of 27 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 98",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,28,650 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitmadras.webp",
        name: "IIT Madras - Indian Institute of Technology [IITM]",
        location: "Chennai, Tamil Nadu | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#1 out of 200 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 85",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,42,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "IIT Kanpur - Indian Institute of Technology [IITK]",
        location: "Kanpur, Uttar Pradesh | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#4 out of 27 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 85",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,29,970 (1st Year Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "IIT Roorkee - Indian Institute of Technology [IITR]",
        location: "Roorkee, Uttarakhand | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#5 out of 27 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 95",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,30,100 (1st Year Fees)",
      },
      {
        rank: "#7",
        logo: "/assets/collegenamelogos/iimbbanglore.webp",
        name: "IIM Bangalore - Indian Institute of Management",
        location: "Bangalore, Karnataka | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/banglore.webp",
        ranking: "#1 out of 50 in India 2019",
        cutoff: "JEE-Adv. 2024 Cut off 99",
        applicationDeadline: "21 June - 07 Aug 2024",
        fees: "₹1,25,000 (1st Year Fees)",
      },
      {
        rank: "#8",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "IIT Guwahati - Indian Institute of Technology [IITG]",
        location: "Guwahati, Assam | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#6 out of 27 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 1021",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,88,250 (1st Year Fees)",
      },
      {
        rank: "#9",
        logo: "/assets/collegenamelogos/bitspilani.webp",
        name: "BITS Pilani (Pilani Campus)",
        location: "Pilani, Rajasthan | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/pilani.webp",
        ranking: "#19 out of 200 in India 2024",
        cutoff: "JEE-Adv. 2024 Cut off 80",
        applicationDeadline: "18 May - 08 Jun 2024",
        fees: "₹5,71,575 (1st Year Fees)",
      },],

      MBA: [
        {
          rank: "#1",
          logo: "/assets/collegenamelogos/iimbbanglore.webp",
          name: "IIM Bangalore - Indian Institute of Management",
          location: "Bangalore, Karnataka | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/banglore.webp",
          ranking: "#1 out of 50 in India 2019",
          cutoff: "CAT 2024 Cut off 99",
          applicationDeadline: "21 June - 07 Aug 2024",
          fees: "₹1,25,000 (1st Year Fees)",
        },
        {
          rank: "#2",
          logo: "/assets/collegenamelogos/iitkharagpur.webp",
          name: "IIT Kharagpur - Indian Institute of Technology",
          location: "Kharagpur, West Bengal | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/madras.webp",
          ranking: "#6 out of 200 in India 2024",
          cutoff: "CAT 2024 Cut off 90",
          applicationDeadline: "10 June - 18 Jun 2024",
          fees: "₹2,62,360 (1st Year Fees)",
        },
        {
          rank: "#3",
          logo: "/assets/collegenamelogos/iitdelhi.webp",
          name: "IIT Delhi - Indian Institute of Technology [IITD]",
          location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/delhi.webp",
          ranking: "#1 out of 27 in India 2024",
          cutoff: "CAT 2024 Cut off 98",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹2,28,650 (1st Year Fees)",
        },
        {
          rank: "#4",
          logo: "/assets/collegenamelogos/iitmadras.webp",
          name: "IIT Madras - Indian Institute of Technology [IITM]",
          location: "Chennai, Tamil Nadu | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/madras.webp",
          ranking: "#1 out of 200 in India 2024",
          cutoff: "CAT 2024 Cut off 85",
          applicationDeadline: "10 June - 18 Jun 2024",
          fees: "₹2,42,000 (1st Year Fees)",
        },
        {
          rank: "#5",
          logo: "/assets/collegenamelogos/iima.webp",
          name: "IIMA - Indian Institute of Management",
          location: "Ahmedabad, Gujarat | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/iima.webp",
          ranking: "#2 out of 50 in India 2019",
          cutoff: "CAT 2024 Cut off 99",
          applicationDeadline: "03 Dec 2024",
          fees: "₹33,00,000 (Total Fees)",
        },
        {
          rank: "#6",
          logo: "/assets/collegenamelogos/iitkanpur.webp",
          name: "IIT Kanpur - Indian Institute of Technology [IITK]",
          location: "Kanpur, Uttar Pradesh | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/kanpur.webp",
          ranking: "#4 out of 27 in India 2024",
          cutoff: "CAT 2024 Cut off 85",
          applicationDeadline: "10 June - 18 Jun 2024",
          fees: "₹2,29,970 (1st Year Fees)",
        },
        {
          rank: "#7",
          logo: "/assets/collegenamelogos/iimbbanglore.webp",
          name: "IIM Bangalore - Indian Institute of Management",
          location: "Bangalore, Karnataka | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/banglore.webp",
          ranking: "#1 out of 50 in India 2019",
          cutoff: "CAT 2024 Cut off 99",
          applicationDeadline: "21 June - 07 Aug 2024",
          fees: "₹1,25,000 (1st Year Fees)",
        },
      ],
      MBBS: [
        {
          rank: "#1",
          logo: "/assets/collegenamelogos/iitguwahati.webp",
          name: "AIIMS Delhi - All India Institute of Medical Sciences",
          location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
          rankingLogo: "/assets/Rankinglogos/guwahati.webp",
          ranking: "#1 out of 50 in India 2024",
          cutoff: "NEET 2024 Cut off 720",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹5,00,000 (Total Fees)",
        },
        {
          rank: "#2",
          logo: "/assets/collegenamelogos/bitspilani.webp",
          name: "CMC Vellore - Christian Medical College",
          location: "Vellore, Tamil Nadu | ⭐ 4.8/5",
          rankingLogo: "/assets/Rankinglogos/pilani.webp",
          ranking: "#2 out of 50 in India 2024",
          cutoff: "NEET 2024 Cut off 690",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹4,50,000 (Total Fees)",
        },
        {
          rank: "#3",
          logo: "/assets/collegenamelogos/iimbbanglore.webp",
          name: "KMC Manipal - Kasturba Medical College",
          location: "Manipal, Karnataka | ⭐ 4.7/5",
          rankingLogo: "/assets/Rankinglogos/banglore.webp",
          ranking: "#3 out of 50 in India 2024",
          cutoff: "NEET 2024 Cut off 680",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹5,75,000 (Total Fees)",
        },
        {
          rank: "#4",
          logo: "/assets/collegenamelogos/iitkanpur.webp",
          name: "AFMC Pune - Armed Forces Medical College",
          location: "Pune, Maharashtra | ⭐ 4.6/5",
          rankingLogo: "/assets/Rankinglogos/kanpur.webp",
          ranking: "#4 out of 50 in India 2024",
          cutoff: "NEET 2024 Cut off 670",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹5,00,000 (Total Fees)",
        },
        {
          rank: "#5",
          logo: "/assets/collegenamelogos/iitkharagpur.webp",
          name: "JIPMER Puducherry - Jawaharlal Institute of Postgraduate Medical Education & Research",
          location: "Puducherry | ⭐ 4.5/5",
          rankingLogo: "/assets/Rankinglogos/madras.webp",
          ranking: "#5 out of 50 in India 2024",
          cutoff: "NEET 2024 Cut off 660",
          applicationDeadline: "14 Mar - 31 Mar 2024",
          fees: "₹4,80,000 (Total Fees)",
        },
      ],
    BBA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/bitspilani.webp",
        name: "BITS Pilani (Pilani Campus)",
        location: "Pilani, Rajasthan | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/pilani.webp",
        ranking: "#19 out of 200 in India 2024",
        cutoff: "CAT 2024 Cut off 80",
        applicationDeadline: "18 May - 08 Jun 2024",
        fees: "₹5,71,575 (1st Year Fees)",
      },
      // Add more BBA colleges
    ],
    BBA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iimbbanglore.webp",
        name: "Symbiosis Centre for Management Studies",
        location: "Pune, Maharashtra | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/banglore.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "SET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 May 2024",
        fees: "₹3,10,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/bitspilani.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/pilani.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 May 2024",
        fees: "₹2,50,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "NMIMS Mumbai - Narsee Monjee Institute of Management Studies",
        location: "Mumbai, Maharashtra | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "NPAT 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 May 2024",
        fees: "₹3,75,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitmadras.webp",
        name: "St. Xavier's College",
        location: "Mumbai, Maharashtra | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "XET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,20,000 (1st Year Fees)",
      },
    ],
    BSc: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "St. Stephen's College",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 98",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹45,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "Loyola College",
        location: "Chennai, Tamil Nadu | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹42,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iimahmedabad.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/iima.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹50,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "Miranda House",
        location: "New Delhi, Delhi NCR | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹48,000 (1st Year Fees)",
      },
    ],
    MSc: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "IIT Bombay - Indian Institute of Technology",
        location: "Mumbai city, Maharashtra | ⭐ 5/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "JAM 2024 Cut off 60",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,30,700 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "IIT Kanpur - Indian Institute of Technology [IITK]",
        location: "Kanpur, Uttar Pradesh | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "JAM 2024 Cut off 55",
        applicationDeadline: "10 June - 18 Jun 2024",
        fees: "₹2,62,360 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "IIT Roorkee - Indian Institute of Technology [IITR]",
        location: "Roorkee, Uttarakhand | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "JAM 2024 Cut off 50",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,30,100 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "IIT Guwahati - Indian Institute of Technology [IITG]",
        location: "Guwahati, Assam | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "JAM 2024 Cut off 45",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹2,88,250 (1st Year Fees)",
      },
    ],BA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "Lady Shri Ram College for Women",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 98",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹45,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Loyola College",
        location: "Chennai, Tamil Nadu | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹42,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹50,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Miranda House",
        location: "New Delhi, Delhi NCR | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹48,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "St. Xavier's College",
        location: "Mumbai, Maharashtra | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,20,000 (1st Year Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iima.webp",
        name: "Hansraj College",
        location: "New Delhi, Delhi NCR | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/iima.webp",
        ranking: "#6 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 78",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹47,000 (1st Year Fees)",
      },
    ],
    BCom: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "Shri Ram College of Commerce",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 98",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹45,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Loyola College",
        location: "Chennai, Tamil Nadu | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹42,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹50,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Narsee Monjee College of Commerce and Economics",
        location: "Mumbai, Maharashtra | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹48,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "St. Xavier's College",
        location: "Mumbai, Maharashtra | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,20,000 (1st Year Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iima.webp",
        name: "Hansraj College",
        location: "New Delhi, Delhi NCR | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/iima.webp",
        ranking: "#6 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 78",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹47,000 (1st Year Fees)",
      },
    ],
    BCA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 May 2024",
        fees: "₹1,75,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Presidency College",
        location: "Bangalore, Karnataka | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 May 2024",
        fees: "₹1,50,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "SRM Institute of Science and Technology",
        location: "Chennai, Tamil Nadu | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 May 2024",
        fees: "₹1,60,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Symbiosis Institute of Computer Studies and Research",
        location: "Pune, Maharashtra | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹1,70,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "Loyola College",
        location: "Chennai, Tamil Nadu | ⭐ 4.4/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 75",
        applicationDeadline: "15 Apr - 10 May 2024",
        fees: "₹1,55,000 (1st Year Fees)",
      },
    ],
    BScNursing: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "All India Institute of Medical Sciences (AIIMS)",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "NEET 2024 Cut off 720",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹5,00,000 (Total Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkharagpur.webp",
        name: "Christian Medical College (CMC)",
        location: "Vellore, Tamil Nadu | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "NEET 2024 Cut off 690",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹4,50,000 (Total Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iimbbanglore.webp",
        name: "Post Graduate Institute of Medical Education and Research (PGIMER)",
        location: "Chandigarh | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/banglore.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "NEET 2024 Cut off 680",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹5,75,000 (Total Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Lady Hardinge Medical College (LHMC)",
        location: "New Delhi, Delhi NCR | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "NEET 2024 Cut off 670",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹5,00,000 (Total Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/bitspilani.webp",
        name: "Armed Forces Medical College (AFMC)",
        location: "Pune, Maharashtra | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/pilani.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "NEET 2024 Cut off 660",
        applicationDeadline: "14 Mar - 31 Mar 2024",
        fees: "₹4,80,000 (Total Fees)",
      },
    ],
    MA: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "Jawaharlal Nehru University (JNU)",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 98",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹45,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Delhi University (DU)",
        location: "New Delhi, Delhi NCR | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹42,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "University of Mumbai",
        location: "Mumbai, Maharashtra | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹50,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Banaras Hindu University (BHU)",
        location: "Varanasi, Uttar Pradesh | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹48,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "Aligarh Muslim University (AMU)",
        location: "Aligarh, Uttar Pradesh | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,20,000 (1st Year Fees)",
      },
    ],
    Diploma: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "SP Jain Institute of Management and Research (SPJIMR)",
        location: "Mumbai, Maharashtra | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 95",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹2,50,000 (Total Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "S.P Mandali's Prin L.N Welingkar Institute of Management Development & Research (WeSchool)",
        location: "Mumbai, Maharashtra | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 90",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹2,30,000 (Total Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "N. L. Dalmia Institute of Management Studies and Research (NLDIMSR)",
        location: "Mumbai, Maharashtra | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 85",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹2,20,000 (Total Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Loyola Institute of Business Administration (LIBA)",
        location: "Chennai, Tamil Nadu | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,00,000 (Total Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "Acharya Nagarjuna University (ANU)",
        location: "Guntur, Andhra Pradesh | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 75",
        applicationDeadline: "15 Apr - 10 May 2024",
        fees: "₹1,90,000 (Total Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iitkharagpur.webp",
        name: "Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU)",
        location: "Nagpur, Maharashtra | ⭐ 4.4/5",
        rankingLogo: "/assets/Rankinglogos/madras.webp",
        ranking: "#6 out of 50 in India 2024",
        cutoff: "MAT 2024 Cut off 70",
        applicationDeadline: "15 Apr - 5 May 2024",
        fees: "₹1,80,000 (Total Fees)",
      },
    ],
    MCom: [
      {
        rank: "#1",
        logo: "/assets/collegenamelogos/iitmumbai.webp",
        name: "Shri Ram College of Commerce (SRCC)",
        location: "New Delhi, Delhi NCR | ⭐ 4.9/5",
        rankingLogo: "/assets/Rankinglogos/mumbai.webp",
        ranking: "#1 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 98",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹45,000 (1st Year Fees)",
      },
      {
        rank: "#2",
        logo: "/assets/collegenamelogos/iitkanpur.webp",
        name: "Loyola College",
        location: "Chennai, Tamil Nadu | ⭐ 4.8/5",
        rankingLogo: "/assets/Rankinglogos/kanpur.webp",
        ranking: "#2 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 95",
        applicationDeadline: "15 Apr - 20 Apr 2024",
        fees: "₹42,000 (1st Year Fees)",
      },
      {
        rank: "#3",
        logo: "/assets/collegenamelogos/iitdelhi.webp",
        name: "Hindu College",
        location: "New Delhi, Delhi NCR | ⭐ 4.7/5",
        rankingLogo: "/assets/Rankinglogos/delhi.webp",
        ranking: "#3 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 90",
        applicationDeadline: "15 Apr - 25 Apr 2024",
        fees: "₹50,000 (1st Year Fees)",
      },
      {
        rank: "#4",
        logo: "/assets/collegenamelogos/iitroorkee.webp",
        name: "Hansraj College",
        location: "New Delhi, Delhi NCR | ⭐ 4.6/5",
        rankingLogo: "/assets/Rankinglogos/roorkee.webp",
        ranking: "#4 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 85",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹48,000 (1st Year Fees)",
      },
      {
        rank: "#5",
        logo: "/assets/collegenamelogos/iitguwahati.webp",
        name: "Madras Christian College (MCC)",
        location: "Chennai, Tamil Nadu | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/guwahati.webp",
        ranking: "#5 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 80",
        applicationDeadline: "15 Apr - 15 May 2024",
        fees: "₹2,20,000 (1st Year Fees)",
      },
      {
        rank: "#6",
        logo: "/assets/collegenamelogos/iima.webp",
        name: "Christ University",
        location: "Bangalore, Karnataka | ⭐ 4.5/5",
        rankingLogo: "/assets/Rankinglogos/iima.webp",
        ranking: "#6 out of 50 in India 2024",
        cutoff: "CUET 2024 Cut off 78",
        applicationDeadline: "15 Apr - 30 Apr 2024",
        fees: "₹47,000 (1st Year Fees)",
      },
    ],
    // Add similar blocks for BTech, BE, MSc, BSc, etc.
  };

  const colleges = collegesData[selectedCourse] || [];

  return (
    <div className="top-colleges-container">
      <h1 className="title">Top Colleges in India</h1>

      <div className="course-buttons">
        {["All", "BTech", "MBA", "BBA", "BA", "BCom", "MSc", "BSc", "BCA", "MA", "BScNursing", "Diploma", "MCom"].map(
          (course) => (
            <button
              key={course}
              onClick={() => handleCourseClick(course)}
              className={selectedCourse === course ? "active-button" : ""}
            >
              {course}
            </button>
          )
        )}
      </div>

      <table className="college-table">
        <thead className="thead">
          <tr>
            <th>Rank</th>
            <th>College</th>
            <th>Ranking</th>
            <th>Cutoff</th>
            <th>Application Deadline</th>
            <th>Fees</th>
          </tr>
        </thead>
        <tbody>
          {colleges.map((college, index) => (
            <tr key={index}>
              <td>{college.rank}</td>
              <td>
                <div className="college-cell">
                  <img src={college.logo} alt="logo" className="college-logo" />
                  <div>
                    <strong>{college.name}</strong>
                    <br />
                    {college.location.split(" | ").map((text, idx, arr) => (
                      <span key={idx}>{idx === 0 ? text : ` | ${text}`}</span>
                    ))}
                  </div>
                </div>
              </td>
              <td>
                <div className="ranking-cell">
                  <img
                    src={college.rankingLogo}
                    alt="ranking logo"
                    className="ranking-logo"
                  />
                  <div>
                    <span style={{ fontWeight: "bold" }}>
                      {college.ranking.split(" ")[0]}
                    </span>{" "}
                    {college.ranking.split(" ").slice(1).join(" ")}
                  </div>
                </div>
              </td>
              <td>
                <div>
                  {college.cutoff.split(" ").map((word, idx) =>
                    idx === college.cutoff.split(" ").length - 1 ? (
                      <span key={idx} style={{ fontWeight: "bold" }}>
                        {word}
                      </span>
                    ) : (
                      word + " "
                    )
                  )}
                </div>
              </td>
              <td>{college.applicationDeadline}</td>
              <td>
                <div>
                  <span style={{ fontWeight: "bold" }}>
                    {college.fees.split(" ")[0]}
                  </span>
                  <br />
                  <span>{college.fees.split(" ").slice(1).join(" ")}</span>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default TopColleges;